In [3]:
import os
os.listdir()


['.ipynb_checkpoints',
 'supermarkets (1).csv',
 'supermarkets (1).xlsx',
 'supermarkets-commas (1).txt',
 'supermarkets-semi-colons (1).txt',
 'supermarkets.json',
 'Untitled.ipynb']

In [5]:
import pandas

In [19]:
df1=pandas.read_csv("supermarkets.csv")
df1.set_index("ID")


Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [22]:
df2=pandas.read_json("supermarkets.json")
df2.set_index("ID")


Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [25]:
df3=pandas.read_excel("supermarkets.xlsx",sheetname=0)
df3


ModuleNotFoundError: No module named 'xlrd'

In [28]:
df4=pandas.read_csv("supermarkets_commas.txt")


FileNotFoundError: File b'supermarkets_commas.txt' does not exist

In [32]:
df2=pandas.read_json("supermarkets.json")
df2.set_index("ID")



Address           City Country  Employees         Name  \
ID                                                                   
1      3666 21st St  San Francisco     USA          8      Madeira   
2    735 Dolores St  San Francisco     USA         15  Bready Shop   
3       332 Hill St  San Francisco     USA         25  Super River   
4      3995 23rd St  San Francisco     USA         10   Ben's Shop   
5   1056 Sanchez St  San Francisco     USA         12      Sanchez   
6   551 Alvarado St  San Francisco     USA         20   Richvalley   

               State  
ID                    
1           CA 94114  
2           CA 94119  
3   California 94114  
4           CA 94114  
5         California  
6           CA 94114

In [36]:
df2=pandas.read_json("supermarkets-semi-colons.txt")
df2


ValueError: Expected object or value

In [39]:
df6=pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df6


ID          Address            City             State Country  \
0   1     3666 21st St   San Francisco          CA 94114     USA   
1   2   735 Dolores St   San Francisco          CA 94119     USA   
2   3      332 Hill St   San Francisco  California 94114     USA   
3   4     3995 23rd St   San Francisco          CA 94114     USA   
4   5  1056 Sanchez St   San Francisco        California     USA   
5   6  551 Alvarado St   San Francisco          CA 94114     USA   

           Name  Employees  
0       Madeira          8  
1   Bready Shop         15  
2   Super River         25  
3    Ben's Shop         10  
4       Sanchez         12  
5    Richvalley         20

In [1]:
df2=pandas.read_json("supermarkets.json")
df2.set_index("ID")


NameError: name 'pandas' is not defined

In [2]:
df6=pandas.read_csv("http://pythonhow.com/supermarkets.csv")
df6


NameError: name 'pandas' is not defined

In [3]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [5]:
import numpy
n=numpy.arange(27)

In [10]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
n=numpy.asarray([[123,12,123,12,33],[],[]])

In [12]:
n

array([[123, 12, 123, 12, 33], [], []], dtype=object)

In [13]:
print n

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-13-ec83713ecbc9>, line 1)

In [14]:
print (n)

[[123, 12, 123, 12, 33] [] []]


In [15]:
numpy.ndarray

numpy.ndarray

In [16]:
import cv2

im_g=cv2.imread("smallgray.png",1)
print(im_g)

In [1]:
nump.ndarry

NameError: name 'nump' is not defined

In [2]:
numpy.ndarray

NameError: name 'numpy' is not defined

In [3]:
import cv2

In [11]:
im_g=cv2.imread("smallgray.png",0)

In [12]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [6]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [7]:
a=[1,2,3]

In [8]:
a[0:2]

[1, 2]

In [16]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [17]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [18]:
im_g[2,4]

182

In [19]:
for i in im_g:

SyntaxError: unexpected EOF while parsing (<ipython-input-19-6580bb7879ef>, line 1)

In [21]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [22]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [23]:
for i in im_g.flat:

SyntaxError: unexpected EOF while parsing (<ipython-input-23-9f0e3f3f8d01>, line 1)

In [24]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [25]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
ims=numpy.hstack((im_g,im_g))

NameError: name 'numpy' is not defined